const restaurants = {
  restaurants_list: [
    {
      id: "11111",
      name: "McDonald's",
      link: "https://www.mcdonalds.com",
      reviews: 5000,
      rating: 4.1,
      price_range_usd: "$",
      menu_link: "https://www.mcdonalds.com/menu",
      reservation_link: "https://www.mcdonalds.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["American", "Fast Food", "Burgers"],
    },
    {
      id: "22222",
      name: "Starbucks",
      link: "https://www.starbucks.com",
      reviews: 4000,
      rating: 4.4,
      price_range_usd: "$$",
      menu_link: "https://www.starbucks.com/menu",
      reservation_link: "https://www.starbucks.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["Coffee", "Bakery", "American"],
    },
    {
      id: "33333",
      name: "KFC",
      link: "https://www.kfc.com",
      reviews: 3000,
      rating: 4.3,
      price_range_usd: "$$",
      menu_link: "https://www.kfc.com/menu",
      reservation_link: "https://www.kfc.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["American", "Chicken", "Fast Food"],
    },
    {
      id: "44444",
      name: "Subway",
      link: "https://www.subway.com",
      reviews: 2500,
      rating: 4.0,
      price_range_usd: "$",
      menu_link: "https://www.subway.com/menu",
      reservation_link: "https://www.subway.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["Sandwiches", "American", "Fast Food"],
    },
    {
      id: "55555",
      name: "Domino's Pizza",
      link: "https://www.dominos.com",
      reviews: 2000,
      rating: 4.5,
      price_range_usd: "$$",
      menu_link: "https://www.dominos.com/menu",
      reservation_link: "https://www.dominos.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["Pizza", "Italian", "Fast Food"],
    },
    {
      id: "66666",
      name: "Taco Bell",
      link: "https://www.tacobell.com",
      reviews: 4000,
      rating: 4.0,
      price_range_usd: "$",
      menu_link: "https://www.tacobell.com/menu",
      reservation_link: "https://www.tacobell.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["Mexican", "Fast Food", "Tacos"],
    },
    {
      id: "77777",
      name: "Chick-fil-A",
      link: "https://www.chick-fil-a.com",
      reviews: 5000,
      rating: 4.7,
      price_range_usd: "$$",
      menu_link: "https://www.chick-fil-a.com/menu",
      reservation_link: "https://www.chick-fil-a.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["American", "Chicken", "Fast Food"],
    },
    {
      id: "88888",
      name: "Wendy's",
      link: "https://www.wendys.com",
      reviews: 3000,
      rating: 4.1,
      price_range_usd: "$",
      menu_link: "https://www.wendys.com/menu",
      reservation_link: "https://www.wendys.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["American", "Fast Food", "Burgers"],
    },
    {
      id: "99999",
      name: "Pizza Hut",
      link: "https://www.pizzahut.com",
      reviews: 3500,
      rating: 4.2,
      price_range_usd: "$$",
      menu_link: "https://www.pizzahut.com/menu",
      reservation_link: "https://www.pizzahut.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["Pizza", "Italian", "Fast Food"],
    },
    {
      id: "101010",
      name: "Panda Express",
      link: "https://www.pandaexpress.com",
      reviews: 4500,
      rating: 4.1,
      price_range_usd: "$",
      menu_link: "https://www.pandaexpress.com/menu",
      reservation_link: "https://www.pandaexpress.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["Chinese", "Fast Food", "Asian"],
    },
    {
      id: "111112",
      name: "In-N-Out Burger",
      link: "https://www.in-n-out.com",
      reviews: 6000,
      rating: 4.8,
      price_range_usd: "$",
      menu_link: "https://www.in-n-out.com/menu",
      reservation_link: "https://www.in-n-out.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: false,
      cuisines: ["American", "Burgers", "Fast Food"],
    },
    {
      id: "121212",
      name: "Dunkin'",
      link: "https://www.dunkindonuts.com",
      reviews: 2500,
      rating: 4.3,
      price_range_usd: "$",
      menu_link: "https://www.dunkindonuts.com/menu",
      reservation_link: "https://www.dunkindonuts.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["Coffee", "Bakery", "American"],
    },
    {
      id: "131313",
      name: "Jack in the Box",
      link: "https://www.jackinthebox.com",
      reviews: 2000,
      rating: 3.9,
      price_range_usd: "$",
      menu_link: "https://www.jackinthebox.com/menu",
      reservation_link: "https://www.jackinthebox.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["American", "Fast Food", "Burgers"],
    },
    {
      id: "141414",
      name: "Shake Shack",
      link: "https://www.shakeshack.com",
      reviews: 3000,
      rating: 4.5,
      price_range_usd: "$$",
      menu_link: "https://www.shakeshack.com/menu",
      reservation_link: "https://www.shakeshack.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["American", "Burgers", "Fast Food"],
    },
    {
      id: "151515",
      name: "Arby's",
      link: "https://www.arbys.com",
      reviews: 1500,
      rating: 4.2,
      price_range_usd: "$$",
      menu_link: "https://www.arbys.com/menu",
      reservation_link: "https://www.arbys.com/reservation",
      featured_image: "https://via.placeholder.com/150",
      has_delivery: true,
      cuisines: ["American", "Fast Food", "Sandwiches"],
    },
  ],
};

export default restaurants;
